

# Google의 provider 구성 정보는 설정하지 않아도 됨
# Spring Security가 Google에 대한 기본 Provider 정보를 이미 내장하고 있기 때문임.
# Spring Security OAuth2 클라이언트 라이브러리는 널리 사용되는 OAuth2 공급자(예: Google, GitHub, Facebook 등)에 대한 기본 설정을 제공하고 있습니다.